server:
  port: 9104
spring:
  application:
    name: leadnews-article
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    nacos:
      discovery:
        namespace: d0442d84-d7d4-40dc-a3b9-eb46435f39c7
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: leadnews-article_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/leadnews_article?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.usian.model.article.pojos
  configuration:
    map-underscore-to-camel-case: false  #是否关闭驼峰到下划线的映射
    cache-enabled: false  #是否开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句
  global-config:
    datacenter-id: 1
    worker-id: 1